name: first workflow
on: 
  push: 
    branches:
     - "main" 
jobs: 
  first_work_job: 
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: run bash cmmand
        run: echo "first workflow"
        shell: bash