name: build docker image
on:
  push:
    branches:
      - 'test'
jobs:
  build-docker:
    name: build-docker-job
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout github
        uses: actions/checkout@v4
      - 
        name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: docker build and push
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: radwakelany123/test:$GITHUB_REF
