name: first workflow
on: 
  push: 
    branches:
     - "main" 
jobs: 
  first_work_job: 
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: run bash cmmand
        run: ls
        shell: bash
      - name: checkout
        uses: actions/checkout@v4
      - name: after chechout
        run: ls
        shell: bash
