name: payments-deploy
on:
  push:
    branches:
      - master
    paths:
      -  'payments/**'
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v6
      - run: cd payments && docker build -t radwakelany123/payments .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push radwakelany123/payments
      - uses: digitalocean/actions-doctl@v6
        with: 
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing 
      - run: kubectl rollout restart deployment payments-deploy
     
