name: ci wrkflow
on: 
  pull_request:
    branches: 
      - 'project'
jobs: 
  ci-workflow:
    name: ci workflow
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
      -
        name: build the app
        run: 'mvn clean package'
        shell: bash
      -
        name: test the app
        run: 'mvn run test'
        shell: bash
        
