
name: second-workflow
on: 
  push: 
    branches:
     - "main" 
jobs: 
  second_work_job: 
    name: first job
    runs-on: ubuntu-latest
    steps:
     - name: run bash command
       run: echo 'second workflow'
       shell: bash
